data_config: "btc_1d_paper"
model: "HybridSSM-Trader_mamba_logret_cost_paper"

name: "HybridSSM-TraderMambaLogReturnCostPaper"
max_epochs: 250
use_volume: true
additional_features: ["Return", "LogReturn", "HLRange", "OCChange", "VolumeChange", "RollingVolatility_7"]

hyperparams:
  optimizer: adam
  lr: 0.0005
  lr_step_size: 50
  lr_gamma: 0.5
  weight_decay: 0.0001
