data_config: "btc_1d_paper"
model: "HybridSSM-Trader_hybrid_gmadl_retce_paper"

name: "HybridSSM-TraderHybrid_gmadl_retce"
max_epochs: 250
use_volume: true
additional_features: ["Return", "LogReturn", "HLRange", "OCChange", "VolumeChange", "RollingVolatility_7"]

hyperparams:
  optimizer: adamw
  lr: 0.0005
  lr_step_size: 50
  lr_gamma: 0.5
  weight_decay: 0.0001
  lr_scheduler: cosine
  lr_cosine_T_max: 250
  lr_cosine_eta_min: 0.000001
